### ISSUE TITLE
Can I pay you for support? 

### ISSUE THREAD

**Issue by toughcustomer** [admineral/OpenAI-Assistant-API-Chat#1]
I am interested in help using this repo.

**Comment by admineral** [comment]
hi, contact me on discord , maybe i can help. ----> .bigbangtheory

**Comment by toughcustomer** [comment]
Thanks ! 

Friend Request Failed.  I guess I need help with discord and Assistant API :) I am hokusai#4254

**Comment by toughcustomer** [comment]
<img width="874" alt="image" src="https://github.com/admineral/OpenAI-Assistant-API-Chat/assets/146129373/9ef423cc-2090-4d7a-a3dd-afb5c517b2d2">

**Comment by admineral** [comment]
Sorry .bigbangtheory Füge mich unter https://discord.com/ hinzu, damit wir reden können! Mein Benutzername ist .bigbangtheory.

**Comment by Speedy2662** [comment]
> .bigbangtheory

Just added you - Speedy2662 is myself. Thanks :)
