### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 2922832737C** [admineral/OpenAI-Assistant-API-Chat#11]
![image](https://github.com/admineral/OpenAI-Assistant-API-Chat/assets/115255509/87edaf26-1664-4fa6-9701-fd22c60f3e2b)
这个shish是什么问题

**Comment by admineral** [comment]
500 = Server Error at openai, not our problem

**Comment by 2922832737C** [comment]
我在本地跑的时候，上传文件的时候，一直找不到那个fileIds，这个是什么问题

**Comment by admineral** [comment]
In the logs 

check your api key ![IMG_4965](https://github.com/admineral/OpenAI-Assistant-API-Chat/assets/50579369/200f93d4-8654-4510-91a6-4b662ee70f03)
