### ISSUE TITLE
Elevenlabs 

### ISSUE THREAD

**Issue by captmikes** [admineral/OpenAI-Assistant-API-Chat#17]
Not an issue, just don't know where to ask. I really could use the TTS from eleven labs and Whisper put in this, dunno if you'd be willing to add it for a fee or something but we have some folks here in that don't type too well and it would sure be cool. Please shoot me an email and let me know mikestrouse@gmail.com I really hope it's possible cuz the last proton in the universe would decay before I could even think of being able to do that lol. Sorry for the intrusion.

**Comment by admineral** [comment]
"Hello, I experimented with ElevenLabs. I think it's very cool, but I think I will wait for the official GPT-4.0 voice API
