### ISSUE TITLE
Is there a limit of files upload?

### ISSUE THREAD

**Issue by yayashuxue** [admineral/OpenAI-Assistant-API-Chat#2]
Hi just wondering how the size, and type of files uploaded affect the performance of the assistants API.

**Comment by admineral** [comment]
You can attach a maximum of 20 (not supported yet in my version) files per Assistant, and they can be at most 512 MB each.

I´m refactoring my code right now, after that i will add multiple file upload

bigger files take more time to index, so it will take up a few seconds

**Comment by yayashuxue** [comment]
Thanks! Yes love to have multiple files!

**Comment by admineral** [comment]
Check out the .env.example , add your Assistant id.... working now on progress feedback during chat and adding multiple file upload...

**Comment by yayashuxue** [comment]
Any update?

**Comment by admineral** [comment]
I have implemented multi-file upload. It's an alpha version, you have to select multiple files at once, not individually but simultaneously. The UI will be adjusted for multi-file upload in the future, but for now, it works
