### ISSUE TITLE
Support Assistant API V2 to use gpt-4o

### ISSUE THREAD

**Issue by vietnguyengit** [admineral/OpenAI-Assistant-API-Chat#21]
Currently, this project doesn't support to use assistant running `gpt-4o` model because it requires Assistant API V2.

```bash
Error in -runAssistant: Error: 400 The requested model 'gpt-4o' cannot be used with the Assistants API in v1. Follow the migration guide to upgrade to v2: https://platform.openai.com/docs/assistants/migration.
```

**Comment by vietnguyengit** [comment]
I'm happy to assist the development of this upgrade if needed, thanks for the work you've done @admineral

**Comment by admineral** [comment]
Yes, a lot changed, needs a complete rework.

7-14 days.

**Comment by vietnguyengit** [comment]
thanks @admineral for your amazing work!

**Comment by admineral** [comment]
Hello, a quick update on the v2 migration. I have now integrated 30 endpoints. I'm taking my time, so I'm on it. Expect another 7 days. I will take a lot of time for the Readmes, code comments, and the whole API architecture.

**Comment by vietnguyengit** [comment]
> Hello, a quick update on the v2 migration. I have now integrated 30 endpoints. I'm taking my time, so I'm on it. Expect another 7 days. I will take a lot of time for the Readmes, code comments, and the whole API architecture.

thank you so much for your hard work! @admineral legend!

**Comment by ditopixels** [comment]
:,D

**Comment by admineral** [comment]
Haha sorry, working on something different

**Comment by admineral** [comment]
Closed until i have time to male a refresh
