### ISSUE TITLE
Is there a way to use an existing assistant ID rather than creating a new assistant?

### ISSUE THREAD

**Issue by OWDadmin** [admineral/OpenAI-Assistant-API-Chat#3]
Currently this works amazingly! However, I'd like to be able to show a list of existing assistants that have been created already and then allow someone to choose which assistant to chat with. Would this be something that could be done easily? I don't know node.js very well, I'm normally a PHP HTML CSS developer lol

**Comment by OWDadmin** [comment]
Hello, yeah that would be awesome! I was actually able to create an updated version of the code that shows a listing of assistants where the welcome form currently exists (hard coded to include the Assistant ID for now) and the upon launch, it bypasses the "Create Assistant" function on the page.tsx file and utilizes the AssistantID from the selected assistant. 

Not being overly familiar with node.js I'm sure your solution will be MUCH more elegant when you are done with it. 

Thanks for the reply!

**Comment by admineral** [comment]
Complete Refactor is 90% done.

**Comment by OWDadmin** [comment]
Thats awesome! Im looking forward to playing around with the updated version!

**Comment by admineral** [comment]
Check out the .env.example , add your Assistant id.... working now on progress feedback during chat and adding multiple file upload...
