### ISSUE TITLE
Wish to see a CLI version of this

### ISSUE THREAD

**Issue by Dan1jel** [admineral/OpenAI-Assistant-API-Chat#5]
Would love to see a CLI version for this, im not really in to the upload file, just send a question with a specific Assistan role. but to not use a webbrowser and use the CLI instead would be perfect if possible :)

**Comment by admineral** [comment]
I think there are some github repos with Assistant via cli. I will link here some as soon as i tested one and its good

**Comment by Dan1jel** [comment]
Not that I know of that could "access" OpenAI API with assistant ID. I know chatGPT but not seen any OpenAI, but if there are any out there that could access the assistant ID, please share it if you know any :)
