### ISSUE TITLE
Pirate?!

### ISSUE THREAD

**Issue by Dan1jel** [admineral/OpenAI-Assistant-API-Chat#6]
i have an assistant ID than i added in the .env and when i ask assistant "who are you" it is correct. But When i start/load the promp it always state in the terminal ` text: { value: 'You are a Pirate! introduce yourself', annotations: [] }` i have looked at OpenAI, Assistant and what i can see/know i have nothing naming a pirate. Is there something im missing or how can i remove this and make the prompt act like it should when loading?

**Comment by admineral** [comment]
Hi, please change the setInitialThreadMessage to , „you are a …. „. In the https://github.com/admineral/OpenAI-Assistant-API-Chat/app/hooks/useChatState.ts#L19

**Comment by Dan1jel** [comment]
Super thanks, because I have set my assistant to be something in the OpenAI can't this be read from that "assistant" or should I add the text I have at OpenAI, in that line also? 

Just trying to know the correct path to take/do. Thanks for the quick reply though.
