### ISSUE TITLE
File uploading into the conversation

### ISSUE THREAD

**Issue by nickelsound** [admineral/OpenAI-Assistant-API-Chat#7]
Please add a possibility to upload a file into the running conversation, not just at the moment the assistant is initialized.

**Comment by admineral** [comment]
Soon! working on the new UI right now

**Comment by admineral** [comment]
I have implemented the ability to upload files during an ongoing conversation, not just at the moment the assistant is initialized. 
You can now select files to upload for each message you send. The selected files will be displayed with an option to remove them before sending the message. This feature has been merged into the main branch and is now available for use.
